<a href="https://colab.research.google.com/github/dmurray1974/tensorFlowCourse/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#In this notebook, were going to cover the most fundamental concept of tensors



In [9]:
#Import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.12.0


In [10]:
#Create Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
# Check the number of Dimensions of a Tensor ( ndim : Number of Dimensions)
scalar.ndim

0

In [12]:
# Create a Vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
# Check the Dimension of the Vector
vector.ndim

1

In [14]:
# Create a Matrix, ( More than 1 Dimension)
matrix = tf.constant([[10, 7, 3],
                     [7, 10, 11]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 7, 10, 11]], dtype=int32)>

In [15]:
matrix.ndim

2

In [16]:
# Create Another Matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]],
                             dtype=tf.float16) #Specify the DataType with dtype Parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [17]:
# Whats the number of dimensions of "Another_Matrix"

another_matrix.ndim

2

In [18]:
# Lets create a tensor
tensor = tf.constant([[[1, 2, 3, 3],
                       [4, 5, 6, 6]],
                      [[7, 8, 9, 9],
                      [10, 11, 12, 12]],
                      [[13, 14, 15, 15],
                       [16, 17, 18, 18]]])

tensor

#Shape = (3,2,4)
# 3 = Arrays
# 2 = List in each Array
# 4 = Items in each List

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  3],
        [ 4,  5,  6,  6]],

       [[ 7,  8,  9,  9],
        [10, 11, 12, 12]],

       [[13, 14, 15, 15],
        [16, 17, 18, 18]]], dtype=int32)>

In [19]:
tensor.ndim   # 3

3

# What we have created so Far
* Scalar : A Single Number
* Vector : A Number with Direction ( e.g Wind Speed and Direction )
* Matrix : a 2 Dimensional array of numbers
* Tensor : an n-dimensional array of numbers ( where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional Tensor is a Vector



# Creating Tensors with tf.variable

#Create the same tensor with tf.variable as above

#nb
* tf.constant is immutable ( You cannot change once created )
* tf.variable is Mutable ( You can change, addd new elements )

In [20]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
#Lets try to change one of the elements in the changeable Tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [23]:
# Lets try with .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [24]:
# Lets try change unchangeable_tensor
unchangeable_tensor[0].assign(7)

AttributeError: ignored

#  Creating Random Tensors

In [ ]:
# Create 2 random (But Same) Tensors
random_1 = tf.random.Generator.from_seed(42)   #Set seed for Reproducability
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)   #Set seed for Reproducability
random_2 = random_2.normal(shape=(3, 2))


# Are They Equal
random_1, random_2, random_1 == random_2


Shuffle The order of elements in a Tensor

In [ ]:
#Shuffke the Tensor ( Valuable for when you want to shuffle data so the inherent order doesnt affect )
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle  Tensor
tf.random.shuffle(not_shuffled)

In [ ]:
not_shuffled

In [ ]:
#Other ways to make Tensors

tf.ones([10, 7])

In [ ]:
tf.zeros(shape=(3, 4))

In [ ]:
#Convert NumPy array into Tensor

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(3,8))
A

In [22]:
A.ndim

2

Getting Information from Tensors

When dealing with Tensors you will probably want to be awre of following Attributes
* Shape.         [ tensor.shape ]
* Rank.           [ tensor.ndim ]
* Axis or Dimension.  [ tensor[0], tensor[:,1] .... ]
* Size.            [ tf.size(tensor) ]

In [26]:
#Create a Rank 4 tensor
rank_4_tensor = tf.zeros( shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor[0][0][0]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [31]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
print("Datatype of every element: {}".format(rank_4_tensor.dtype))
print("Number of Dimensions: {}".format(rank_4_tensor.ndim))
print("Size of Tensor: {}".format(tf.size(rank_4_tensor)))
print("Number of Elements in Tensor: {}".format(rank_4_tensor.shape))
print("Elemnts along the 0 Axis: {}".format(rank_4_tensor.shape[0]))
print("Elemnts along the Last Axis: {}".format(rank_4_tensor.shape[-1]))





Datatype of every element: <dtype: 'float32'>
Number of Dimensions: 4
Size of Tensor: 120
Shape of Tensor: (2, 3, 4, 5)
Elemnts along the 0 Axis: 2
Elemnts along the Last Axis: 5


Indexing Tensors

Tensors can be indexed just like Python Lists

In [36]:
#Get the first 2 elements of each Dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [39]:
#Get first element from each dimension except for the final one

rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [42]:
#Create a Rank2 Tensor
rank_2_tensor = tf.constant([[10,7], [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
from tensorflow.python.ops.gen_array_ops import rank
#Get the last item of each of the 2 Tensors
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [46]:
#Add in Extra Dimension to rank_2_tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [53]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

Tensor Operations Video 23

** Basic Operations
+, -, *, /

In [57]:
#You can add values to a Tensor using the Addition[+] operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [58]:
#Multiplation *
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [59]:
#Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [60]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

It is better to use the TensorFlow Builtin Functions to get better performance especially on large Tensors. It will benefit from GPU processing

** Matrix Multiplication **

In Machine Learning, Matrix  Multiplication is one of the most common Tensor Operations

http://matrixmultiplication.xyz


In [64]:
#Matrix Multiplication in TensorFlow. tf.linalg.matmul
print("Original Tensor: {}".format(tensor))
tf.matmul(tensor, tensor)

Original Tensor: [[10  7]
 [ 3  4]]


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [68]:
# Matrix Multiplication with Python Operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [67]:
# Example of Matrix Multiplication https://www.mathsisfun.com/algebra/matrix-multiplying.html

t1 = tf.constant([[1,2,5],
                  [7,2,1],
                   [3,3,3]])
print(t1)

t2 = tf.constant([[3,5],
                  [7,6],
                   [1,8]])

print(t2)

tf.matmul(t1, t2)

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 5]
 [7 6]
 [1 8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22, 57],
       [36, 55],
       [33, 57]], dtype=int32)>

Matrix Multiplication Rules
1. The inner Dimensions must Match
2. The resulting matrix has the shape of the Inner Dimensions

i.e. [3,2], [2,3] where 2 is the Inner Dimension as 2 == 2
NOT [3,4], [3,2]. as 4 != 3