<a href="https://colab.research.google.com/github/dmurray1974/tensorFlowCourse/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#In this notebook, were going to cover the most fundamental concept of tensors



Hello World


In [ ]:
#Import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.12.0


In [ ]:
#Create Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of Dimensions of a Tensor ( ndim : Number of Dimensions)
scalar.ndim

0

In [ ]:
# Create a Vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the Dimension of the Vector
vector.ndim

1

In [ ]:
# Create a Matrix, ( More than 1 Dimension)
matrix = tf.constant([[10, 7, 3],
                     [7, 10, 11]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 7, 10, 11]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create Another Matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]],
                             dtype=tf.float16) #Specify the DataType with dtype Parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Whats the number of dimensions of "Another_Matrix"

another_matrix.ndim

2

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[1, 2, 3, 3],
                       [4, 5, 6, 6]],
                      [[7, 8, 9, 9],
                      [10, 11, 12, 12]],
                      [[13, 14, 15, 15],
                       [16, 17, 18, 18]]])

tensor

#Shape = (3,2,4)
# 3 = Arrays
# 2 = List in each Array
# 4 = Items in each List

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  3],
        [ 4,  5,  6,  6]],

       [[ 7,  8,  9,  9],
        [10, 11, 12, 12]],

       [[13, 14, 15, 15],
        [16, 17, 18, 18]]], dtype=int32)>

In [ ]:
tensor.ndim   # 3

3

# What we have created so Far
* Scalar : A Single Number
* Vector : A Number with Direction ( e.g Wind Speed and Direction )
* Matrix : a 2 Dimensional array of numbers
* Tensor : an n-dimensional array of numbers ( where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional Tensor is a Vector



# Creating Tensors with tf.variable

#Create the same tensor with tf.variable as above

#nb
* tf.constant is immutable ( You cannot change once created )
* tf.variable is Mutable ( You can change, addd new elements )

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Lets try to change one of the elements in the changeable Tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# Lets try with .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Lets try change unchangeable_tensor
unchangeable_tensor[0].assign(7)

AttributeError: ignored

#  Creating Random Tensors

In [ ]:
# Create 2 random (But Same) Tensors
random_1 = tf.random.Generator.from_seed(42)   #Set seed for Reproducability
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)   #Set seed for Reproducability
random_2 = random_2.normal(shape=(3, 2))


# Are They Equal
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffle The order of elements in a Tensor

In [ ]:
#Shuffke the Tensor ( Valuable for when you want to shuffle data so the inherent order doesnt affect )
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle  Tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Other ways to make Tensors

tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Convert NumPy array into Tensor

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>